In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
birds_df = pd.read_csv(
    "../cleaned_data/birds_cleaned.csv"
)

birds_df.head()

,AOU_Code,AcceptedTSN,Admin_Sheet,Admin_Unit_Code,Common_Name,Date,Distance,Disturbance,End_Time,Flyover_Observed,Habitat,Humidity,ID_Method,Initial_Three_Min_Cnt,Interval_Length,Location_Type,NPSTaxonCode,Observer,PIF_Watchlist_Status,Plot_Name,Regional_Stewardship_Status,Scientific_Name,Sex,Site_Name,Sky,Start_Time,Temperature,Visit,Wind,Year,Month,Month_Name,Quarter,Season
0,EATO,179276.0,ANTI,ANTI,Eastern Towhee,2018-05-22,<= 50 Meters,No effect on count,06:29:00,False,Forest,79.400002,Singing,True,0-2.5 min,Forest,83803.0,Elizabeth Oswald,False,ANTI-0036,True,Pipilo erythrophthalmus,Undetermined,ANTI 1,Cloudy/Overcast,06:19:00,19.9,1,Calm (< 1 mph) smoke rises vertically,2018,5,May,2,Spring
1,WBNU,178775.0,ANTI,ANTI,White-breasted Nuthatch,2018-05-22,<= 50 Meters,No effect on count,06:29:00,False,Forest,79.400002,Calling,True,0-2.5 min,Forest,90935.0,Elizabeth Oswald,False,ANTI-0036,False,Sitta carolinensis,Unknown,ANTI 1,Cloudy/Overcast,06:19:00,19.9,1,Calm (< 1 mph) smoke rises vertically,2018,5,May,2,Spring
2,RBWO,178195.0,ANTI,ANTI,Red-bellied Woodpecker,2018-05-22,50 - 100 Meters,No effect on count,06:29:00,False,Forest,79.400002,Calling,False,2.5 - 5 min,Forest,84865.0,Elizabeth Oswald,False,ANTI-0036,False,Melanerpes carolinus,Unknown,ANTI 1,Cloudy/Overcast,06:19:00,19.9,1,Calm (< 1 mph) smoke rises vertically,2018,5,May,2,Spring
3,OROR,179064.0,ANTI,ANTI,Orchard Oriole,2018-05-22,<= 50 Meters,No effect on count,06:29:00,False,Forest,79.400002,Singing,False,2.5 - 5 min,Forest,93634.0,Elizabeth Oswald,False,ANTI-0036,False,Icterus spurius,Unknown,ANTI 1,Cloudy/Overcast,06:19:00,19.9,1,Calm (< 1 mph) smoke rises vertically,2018,5,May,2,Spring
4,NOMO,178620.0,ANTI,ANTI,Northern Mockingbird,2018-05-22,<= 50 Meters,No effect on count,06:29:00,False,Forest,79.400002,Visualization,False,2.5 - 5 min,Forest,88394.0,Elizabeth Oswald,False,ANTI-0036,False,Mimus polyglottos,Unknown,ANTI 1,Cloudy/Overcast,06:19:00,19.9,1,Calm (< 1 mph) smoke rises vertically,2018,5,May,2,Spring


# Bird Species Observation Analysis

## Objective

The goal of this project is to analyze bird observation data collected from forest and grassland habitats.

The analysis focuses on:

- Temporal patterns
- Spatial distribution
- Species diversity
- Environmental influences
- Habitat comparisons

The objective is to generate ecological insights that can support biodiversity monitoring and conservation planning.

In [3]:
summary = pd.DataFrame({
    "Metric": [
        "Total Observations",
        "Unique Species",
        "Forest Observations",
        "Grassland Observations"
    ],
    "Value": [
        15372,
        127,
        8546,
        6826
    ]
})

summary

,Metric,Value
0,Total Observations,15372
1,Unique Species,127
2,Forest Observations,8546
3,Grassland Observations,6826


# Executive Summary

The dataset contains 15,372 bird observations covering 127 unique species across forest and grassland habitats.

Forest habitats generated more observations than grasslands; however, both habitats exhibited nearly identical species diversity.

Bird activity was highest during summer months, particularly June.

Environmental conditions such as moderate temperatures, high humidity, low wind speeds, and minimal disturbance were associated with higher observation rates.

Most species were identified through acoustic methods, especially singing behavior.

The findings highlight the ecological importance of both forest and grassland ecosystems and support balanced conservation strategies.

In [4]:
findings = pd.DataFrame({
    "Category":[
        "Most Active Month",
        "Top Species",
        "Top Biodiversity Unit",
        "Most Active Unit",
        "Highest Diversity Habitat",
        "Most Common Sky Condition"
    ],

    "Finding":[
        "June",
        "Northern Cardinal",
        "MONO",
        "ANTI",
        "Forest",
        "Partly Cloudy"
    ]
})

findings

,Category,Finding
0,Most Active Month,June
1,Top Species,Northern Cardinal
2,Top Biodiversity Unit,MONO
3,Most Active Unit,ANTI
4,Highest Diversity Habitat,Forest
5,Most Common Sky Condition,Partly Cloudy


# Conservation Insights

### Habitat Importance

Forest habitats produced more observations.

However, grasslands supported nearly equal species diversity.

This suggests that both habitat types contribute significantly to regional biodiversity.

### Biodiversity Hotspots

MONO, MANA, ANTI, and CHOH exhibited the highest species richness.

These locations should be prioritized for biodiversity monitoring.

### Environmental Conditions

Bird activity was highest during:

- Moderate temperatures
- High humidity
- Calm wind conditions
- Low disturbance periods

Future surveys should be scheduled during similar environmental conditions.

In [5]:
birds_df["NPSTaxonCode"] = (
    birds_df["NPSTaxonCode"]
    .fillna(-1)
)

# Recommendations

1. Continue monitoring both forest and grassland habitats.

2. Prioritize conservation efforts in MONO, MANA, ANTI, and CHOH.

3. Conduct surveys during favorable weather conditions.

4. Use acoustic monitoring methods because singing and calling accounted for most detections.

5. Increase monitoring efforts for rare species observed infrequently.

# Conclusion

The Bird Species Observation Analysis identified significant temporal, spatial, species-level, and environmental patterns within the monitoring dataset.

A total of 127 species were recorded across 15,372 observations.

Forest habitats produced the highest number of observations, while both forest and grassland habitats demonstrated nearly identical species diversity.

Environmental conditions strongly influenced observation success, with calm and moderately warm conditions producing the highest activity levels.

The results support continued biodiversity monitoring and balanced habitat conservation strategies.

In [6]:
import sqlite3

conn = sqlite3.connect(
    "../database/bird_species.db"
)

conn.close()

print("Database Closed Successfully")

Database Closed Successfully
